### ISSUE TITLE
[Bug] globby error during running on >=1.1.3

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [sysgears/mochapack#27]
- [ ] I'd be willing to submit the fix

**Describe the bug**

A version < 1.1.3 seems to run okay still, but after the mochapack dependency updates something seems to have broken. I get the following error when I attempt to run mochapack on >=1.1.3:

```
D:\Projects\JavaScript\JS\MasterClass>npm run test

> js_master_class@1.0.0 test D:\Projects\JavaScript\JS\MasterClass
> mochapack --webpack-config webpack.config.test.js --require ./test/test_helper.js ./test/index.spec.js

D:\Projects\JavaScript\JS\MasterClass\node_modules\globby\index.js:50
                ...taskOptions
                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\JavaScript\JS\MasterClass\node_modules\mochapack\lib\util\glob.js:16:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**To Reproduce**

run `mochapack --webpack-config webpack.config.test.js --require ./test/test_helper.js ./test/index.spec.js`. The files that are required for reproduction contain:

webpack.config.js
```javascript
const path 	= require("path"),
      webpack 	= require("webpack"),
      merge     = require("webpack-merge"),
      APP_DIR   = path.resolve(__dirname, "src"),
      BUILD_DIR = path.resolve(__dirname, "build");


let commonConfig = {
  target: "node",
  output: {
    path: 	BUILD_DIR,
    publicPath: "/",
    filename: 	"bundle.js"
  },
  resolve: {
    extensions: [ ".ts", ".js" ]
  },
  module: {
    rules: [
      {
        test: 	 /\.js$/,
        loader:  "babel-loader",
        include: APP_DIR
      }, {
        test:    /\.ts$/,
        loader: "awesome-typescript-loader",
        include: APP_DIR,
        options: {
          // NOTE: serves as a handy switch for prototyping needs:
          transpileOnly: true
        }
      }
    ]
  }
};

module.exports = env =>
  env && env.production
  ? merge(commonConfig, {
      mode: "production",
      entry: [
        `${APP_DIR}/index.js` 
      ]
    })
  : merge(commonConfig, {
      mode: "development",
      entry: [
        "webpack/hot/only-dev-server", // Prevents reloading during errors.
        `${APP_DIR}/index.js` 
      ],
      plugins: [
        new webpack.HotModuleReplacementPlugin()
      ]
    });

```

webpack.config.test.js
```javascript
let config   = require("./webpack.config"),
    path     = require("path"),
    TEST_DIR = path.resolve(__dirname, "test");

config.entry = [
  `${TEST_DIR}/index.spec.js` 
];

config.module = {
  rules: [
    {
      test:    /\.js$/,
      loader:  "babel-loader",
      include: TEST_DIR
    }, {
      test:    /\.ts$/,
      loader: "awesome-typescript-loader",
      include: TEST_DIR,
      options: {
        // Currently not used, since TS gives a bit of a headache on EcmaNext:
        // NOTE: serves as a handy switch for prototyping needs:
        transpileOnly: true
      }
    }
  ]
};

module.exports = config;
```

```javascript
"use strict";

var chai  	   = require("chai"),
    chaiAsPromised = require("chai-as-promised");

chai.use(chaiAsPromised);
chai.should();
```

(Possibly) relevant libraries in package.json (I haven't omitted the babel-plugins, in case they turn out to be useful in the bug hunt):

```javascript
"devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/plugin-proposal-do-expressions": "^7.5.0",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/plugin-proposal-export-namespace-from": "^7.5.2",
    "@babel/plugin-proposal-function-bind": "^7.2.0",
    "@babel/plugin-proposal-function-sent": "^7.5.0",
    "@babel/plugin-proposal-json-strings": "^7.2.0",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.2.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.4.4",
    "@babel/plugin-proposal-numeric-separator": "^7.2.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "@babel/plugin-proposal-pipeline-operator": "^7.5.0",
    "@babel/plugin-proposal-throw-expressions": "^7.2.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-syntax-import-meta": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@types/html-webpack-plugin": "^3.2.1",
    "@types/mocha": "^5.2.7",
    "@types/node": "^12.7.3",
    "@types/webpack-env": "^1.14.0",
    "awesome-typescript-loader": "^5.2.1",
    "babel-loader": "^8.0.6",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "eslint": "^6.3.0",
    "loglevel": "^1.6.3",
    "mocha": "^6.2.0",
    "mochapack": "^1.1.2",
    "sinon": "^7.4.1",
    "typescript": "^3.6.2",
    "webpack": "^4.39.3",
    "webpack-cli": "^3.3.7",
    "webpack-merge": "^4.2.2"
  }
```

the contents of the file `index.spec.js` are irrelevant (a file can be empty and the issue will still persist).

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 8.1.2
 - Mochapack version >=1.1.3
 - Webpack version 4.39.3

**Comment by 4lph4-Ph4un** [comment]
This was solved by updating both node and npm-version as they were both pretty old.
