### ISSUE TITLE
[Bug] imports do not work with sass-loader and stdin template

### ISSUE THREAD

**Issue by pscheit** [sysgears/mochapack#71]
- [ ] I'd be willing to submit the fix

**Describe the bug**

I got the following webpack config for the sass-loader:

```
              {
                "loader": "sass-loader",
                "options": {
                  "sourceMap": true,
                  "outputStyle": "expanded",
                  "implementation": {
                    "info": "dart-sass\t1.22.10\t(Sass Compiler)\t[Dart]\ndart2js\t2.4.1\t(Dart Compiler)\t[Dart]",
                    "types": {}
                  },
                  "data": "@import \"~assets/scss/_replacements/vuetify-main.scss\""
                }
              }
```
Error in ./node_modules/vuetify/src/components/VCalendar/mixins/calendar-with-events.sass

  Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
  ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
  Can't find stylesheet to import.
    ╷
  2 │ @import 'vuetify-variables';
    │         ^^^^^^^^^^^^^^^^^^^
    ╵
    app/assets/scss/_replacements/vuetify-main.scss 2:9  @import
    stdin 1:9                                            root stylesheet
        in about:/app/assets/scss/_replacements/vuetify-main.scss (line 2, column 9)
      at /app/node_modules/webpack/lib/NormalModule.js:316:20
      at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
      at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
      at /app/node_modules/sass-loader/dist/index.js:89:7
```

I can try all variations of the import, but the sub-import in the imported file cannot be resolved.

**To Reproduce**

add an import in the stdin template for sass-loader (see above)

**Environment if relevant (please complete the following information):**

 - OS: Linux on Docker
 - Node version v12.14.1
 - Mochapack version 2.0.0
 - Webpack version 4.43.0

Thanks for giving me an idea. Is it the ~ in the import patH?

**Comment by Niush** [comment]
Any progress here? I am facing same problem testing with Vuetify.

```
ERROR  Failed to compile with 28 errors
error  in ./node_modules/vuetify/src/components/VApp/VApp.sass

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import '../../styles/styles.sass'
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```
and bunch more **sass** and **scss** build fail errors.

**Comment by phillt** [comment]
This seems to still be happening. I've [posted a question in SOF](https://stackoverflow.com/questions/68839434/sasserror-cant-find-stylesheet-to-import-not-from-node-modules-using-mocha) in case anyone wants to check if you're coming from the future.

**Comment by josephlavin** [comment]
@larixer:  Thank you for your help.

I can not get any of those configurations under the `With CSS-Modules`  to work.  I am now thinking this is a Webpack 4 vs 5 issue.  Mainly that I can not figure out the Webpack 5 equivalent of those configurations.

The `null-loader` does appear to avoid the issue.  However that [that is being depricated](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#deprecated-loaders) and I am not having any luck with aliases.

**Comment by larixer** [comment]
@josephlavin 

> I can not get any of those configurations under the `With CSS-Modules` to work. I am now thinking this is a Webpack 4 vs 5 issue. Mainly that I can not figure out the Webpack 5 equivalent of those configurations.

The compilation is not `mochapack` issue at all. This can easily be seen if you update your `webpack.mix.js` and add a line:
```
mix.webpackConfig({target: 'node'});
``` 
after that comment out the line in your `setup.js`:
```
// require('jsdom-global')();
```
In your example repo, there are two mistakes:
1. The tests are not built for `node` target, the `mochapack` is pretty clear that webpack must be configured to build for `node` target
2. You are requiring `jsdom-global` in `setup.js` which is invoked BEFORE the compilation and it makes many tools you use "think" that they are running in the browser environment, this interferes with the compilation process and you see the error.  You should require `jsdom` in your tests and not via `--require` option.

**Comment by josephlavin** [comment]
@larixer: Thank you for the detailed explanation.  It appears as if all my troubles were caused by using `--require` instead of `--include`. 

In case anyone else encounters a similar issue here are a few more details:
> You are requiring `jsdom-global` in `setup.js` which is invoked BEFORE the compilation and it makes many tools you use "think" that they are running in the browser environment, this interferes with the compilation process and you see the error.

Thank you again!
